on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        if: github.ref == 'refs/heads/master'
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install-ci-test
      - run: npm run deploy
        if: github.ref == 'refs/heads/master'
