on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm install-ci-test
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        if: github.ref == 'refs/heads/master'
      - run: |
          true
        if: github.ref == 'refs/heads/master'
